import type { ExampleConfig } from '#/lib/types'

const config = {
  metadata: {
    title: 'Multi-Layer — Zoom Crossfade',
    description:
      'Heatmap at low zoom crossfades to magnitude-scaled circles — transition range is fully controllable',
    tier: 'intermediate',
  },
  config: {
    sources: [
      {
        id: 'earthquakes',
        type: 'geojson',
        data: 'https://docs.mapbox.com/mapbox-gl-js/assets/earthquakes.geojson',
      },
    ],
    styles: [
      {
        source: 'earthquakes',
        type: 'heatmap',
        paint: {
          'heatmap-weight': [
            'interpolate',
            ['linear'],
            ['get', 'mag'],
            0,
            0,
            6,
            1,
          ],
          'heatmap-intensity': [
            'interpolate',
            ['linear'],
            ['zoom'],
            0,
            1,
            9,
            3,
          ],
          'heatmap-color': [
            'interpolate',
            ['linear'],
            ['heatmap-density'],
            0,
            'rgba(0, 0, 0, 0)',
            0.2,
            '#2c7bb6',
            0.4,
            '#abd9e9',
            0.6,
            '#ffffbf',
            0.8,
            '#fdae61',
            1.0,
            '#d7191c',
          ],
          'heatmap-radius': ['interpolate', ['linear'], ['zoom'], 0, 2, 9, 20],
          'heatmap-opacity': [
            'interpolate',
            ['linear'],
            ['zoom'],
            '@@#params.transition_start',
            '@@#params.opacity',
            '@@#params.transition_end',
            0,
          ],
        },
      },
      {
        source: 'earthquakes',
        type: 'circle',
        paint: {
          'circle-radius': [
            'interpolate',
            ['linear'],
            ['get', 'mag'],
            1,
            ['*', 2, '@@#params.circle_scale'],
            3,
            ['*', 4, '@@#params.circle_scale'],
            5,
            ['*', 8, '@@#params.circle_scale'],
            7,
            ['*', 14, '@@#params.circle_scale'],
          ],
          'circle-color': [
            'interpolate',
            ['linear'],
            ['get', 'mag'],
            1,
            '#2c7bb6',
            3,
            '#abd9e9',
            5,
            '#fdae61',
            7,
            '#d7191c',
          ],
          'circle-opacity': [
            'interpolate',
            ['linear'],
            ['zoom'],
            '@@#params.transition_start',
            0,
            '@@#params.transition_end',
            '@@#params.opacity',
          ],
          'circle-stroke-width': 1,
          'circle-stroke-opacity': [
            'interpolate',
            ['linear'],
            ['zoom'],
            '@@#params.transition_start',
            0,
            '@@#params.transition_end',
            1,
          ],
          'circle-stroke-color': '#ffffff',
        },
      },
    ],
  },
  params_config: [
    {
      key: 'transition_start',
      default: 5,
      min: 0,
      max: 14,
      step: 1,
    },
    {
      key: 'transition_end',
      default: 7,
      min: 2,
      max: 16,
      step: 1,
    },
    {
      key: 'circle_scale',
      default: 1,
      min: 0.5,
      max: 3,
      step: 0.1,
    },
    {
      key: 'opacity',
      default: 0.8,
      min: 0,
      max: 1,
      step: 0.05,
    },
  ],
  legend_config: {
    type: 'gradient',
    items: [
      { label: 'Low magnitude', value: '#2c7bb6' },
      { label: 'High magnitude', value: '#d7191c' },
    ],
  },
} satisfies ExampleConfig

export default config
