/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidelinesIndexRouteImport } from './routes/guidelines/index'
import { Route as GuidelinesTypesRouteImport } from './routes/guidelines/types'
import { Route as GuidelinesParamsRouteImport } from './routes/guidelines/params'
import { Route as GuidelinesLegendsRouteImport } from './routes/guidelines/legends'
import { Route as GuidelinesFunctionsRouteImport } from './routes/guidelines/functions'
import { Route as GuidelinesExpressionsRouteImport } from './routes/guidelines/expressions'

const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesIndexRoute = GuidelinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidelinesRoute,
} as any)
const GuidelinesTypesRoute = GuidelinesTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => GuidelinesRoute,
} as any)
const GuidelinesParamsRoute = GuidelinesParamsRouteImport.update({
  id: '/params',
  path: '/params',
  getParentRoute: () => GuidelinesRoute,
} as any)
const GuidelinesLegendsRoute = GuidelinesLegendsRouteImport.update({
  id: '/legends',
  path: '/legends',
  getParentRoute: () => GuidelinesRoute,
} as any)
const GuidelinesFunctionsRoute = GuidelinesFunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => GuidelinesRoute,
} as any)
const GuidelinesExpressionsRoute = GuidelinesExpressionsRouteImport.update({
  id: '/expressions',
  path: '/expressions',
  getParentRoute: () => GuidelinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guidelines': typeof GuidelinesRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/presentation': typeof PresentationRoute
  '/guidelines/expressions': typeof GuidelinesExpressionsRoute
  '/guidelines/functions': typeof GuidelinesFunctionsRoute
  '/guidelines/legends': typeof GuidelinesLegendsRoute
  '/guidelines/params': typeof GuidelinesParamsRoute
  '/guidelines/types': typeof GuidelinesTypesRoute
  '/guidelines/': typeof GuidelinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/playground': typeof PlaygroundRoute
  '/presentation': typeof PresentationRoute
  '/guidelines/expressions': typeof GuidelinesExpressionsRoute
  '/guidelines/functions': typeof GuidelinesFunctionsRoute
  '/guidelines/legends': typeof GuidelinesLegendsRoute
  '/guidelines/params': typeof GuidelinesParamsRoute
  '/guidelines/types': typeof GuidelinesTypesRoute
  '/guidelines': typeof GuidelinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guidelines': typeof GuidelinesRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/presentation': typeof PresentationRoute
  '/guidelines/expressions': typeof GuidelinesExpressionsRoute
  '/guidelines/functions': typeof GuidelinesFunctionsRoute
  '/guidelines/legends': typeof GuidelinesLegendsRoute
  '/guidelines/params': typeof GuidelinesParamsRoute
  '/guidelines/types': typeof GuidelinesTypesRoute
  '/guidelines/': typeof GuidelinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/guidelines'
    | '/playground'
    | '/presentation'
    | '/guidelines/expressions'
    | '/guidelines/functions'
    | '/guidelines/legends'
    | '/guidelines/params'
    | '/guidelines/types'
    | '/guidelines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/playground'
    | '/presentation'
    | '/guidelines/expressions'
    | '/guidelines/functions'
    | '/guidelines/legends'
    | '/guidelines/params'
    | '/guidelines/types'
    | '/guidelines'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/guidelines'
    | '/playground'
    | '/presentation'
    | '/guidelines/expressions'
    | '/guidelines/functions'
    | '/guidelines/legends'
    | '/guidelines/params'
    | '/guidelines/types'
    | '/guidelines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GuidelinesRoute: typeof GuidelinesRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  PresentationRoute: typeof PresentationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines/': {
      id: '/guidelines/'
      path: '/'
      fullPath: '/guidelines/'
      preLoaderRoute: typeof GuidelinesIndexRouteImport
      parentRoute: typeof GuidelinesRoute
    }
    '/guidelines/types': {
      id: '/guidelines/types'
      path: '/types'
      fullPath: '/guidelines/types'
      preLoaderRoute: typeof GuidelinesTypesRouteImport
      parentRoute: typeof GuidelinesRoute
    }
    '/guidelines/params': {
      id: '/guidelines/params'
      path: '/params'
      fullPath: '/guidelines/params'
      preLoaderRoute: typeof GuidelinesParamsRouteImport
      parentRoute: typeof GuidelinesRoute
    }
    '/guidelines/legends': {
      id: '/guidelines/legends'
      path: '/legends'
      fullPath: '/guidelines/legends'
      preLoaderRoute: typeof GuidelinesLegendsRouteImport
      parentRoute: typeof GuidelinesRoute
    }
    '/guidelines/functions': {
      id: '/guidelines/functions'
      path: '/functions'
      fullPath: '/guidelines/functions'
      preLoaderRoute: typeof GuidelinesFunctionsRouteImport
      parentRoute: typeof GuidelinesRoute
    }
    '/guidelines/expressions': {
      id: '/guidelines/expressions'
      path: '/expressions'
      fullPath: '/guidelines/expressions'
      preLoaderRoute: typeof GuidelinesExpressionsRouteImport
      parentRoute: typeof GuidelinesRoute
    }
  }
}

interface GuidelinesRouteChildren {
  GuidelinesExpressionsRoute: typeof GuidelinesExpressionsRoute
  GuidelinesFunctionsRoute: typeof GuidelinesFunctionsRoute
  GuidelinesLegendsRoute: typeof GuidelinesLegendsRoute
  GuidelinesParamsRoute: typeof GuidelinesParamsRoute
  GuidelinesTypesRoute: typeof GuidelinesTypesRoute
  GuidelinesIndexRoute: typeof GuidelinesIndexRoute
}

const GuidelinesRouteChildren: GuidelinesRouteChildren = {
  GuidelinesExpressionsRoute: GuidelinesExpressionsRoute,
  GuidelinesFunctionsRoute: GuidelinesFunctionsRoute,
  GuidelinesLegendsRoute: GuidelinesLegendsRoute,
  GuidelinesParamsRoute: GuidelinesParamsRoute,
  GuidelinesTypesRoute: GuidelinesTypesRoute,
  GuidelinesIndexRoute: GuidelinesIndexRoute,
}

const GuidelinesRouteWithChildren = GuidelinesRoute._addFileChildren(
  GuidelinesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GuidelinesRoute: GuidelinesRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  PresentationRoute: PresentationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
