/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidelinesIndexRouteImport } from './routes/guidelines/index'
import { Route as GuidelinesTypesRouteImport } from './routes/guidelines/types'
import { Route as GuidelinesParamsRouteImport } from './routes/guidelines/params'
import { Route as GuidelinesLegendsRouteImport } from './routes/guidelines/legends'
import { Route as GuidelinesFunctionsRouteImport } from './routes/guidelines/functions'
import { Route as GuidelinesExpressionsRouteImport } from './routes/guidelines/expressions'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoOrpcTodoRouteImport } from './routes/demo/orpc-todo'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesIndexRoute = GuidelinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidelinesRoute,
} as any)
const GuidelinesTypesRoute = GuidelinesTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => GuidelinesRoute,
} as any)
const GuidelinesParamsRoute = GuidelinesParamsRouteImport.update({
  id: '/params',
  path: '/params',
  getParentRoute: () => GuidelinesRoute,
} as any)
const GuidelinesLegendsRoute = GuidelinesLegendsRouteImport.update({
  id: '/legends',
  path: '/legends',
  getParentRoute: () => GuidelinesRoute,
} as any)
const GuidelinesFunctionsRoute = GuidelinesFunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => GuidelinesRoute,
} as any)
const GuidelinesExpressionsRoute = GuidelinesExpressionsRouteImport.update({
  id: '/expressions',
  path: '/expressions',
  getParentRoute: () => GuidelinesRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrpcTodoRoute = DemoOrpcTodoRouteImport.update({
  id: '/demo/orpc-todo',
  path: '/demo/orpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guidelines': typeof GuidelinesRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/presentation': typeof PresentationRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/guidelines/expressions': typeof GuidelinesExpressionsRoute
  '/guidelines/functions': typeof GuidelinesFunctionsRoute
  '/guidelines/legends': typeof GuidelinesLegendsRoute
  '/guidelines/params': typeof GuidelinesParamsRoute
  '/guidelines/types': typeof GuidelinesTypesRoute
  '/guidelines/': typeof GuidelinesIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/playground': typeof PlaygroundRoute
  '/presentation': typeof PresentationRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/guidelines/expressions': typeof GuidelinesExpressionsRoute
  '/guidelines/functions': typeof GuidelinesFunctionsRoute
  '/guidelines/legends': typeof GuidelinesLegendsRoute
  '/guidelines/params': typeof GuidelinesParamsRoute
  '/guidelines/types': typeof GuidelinesTypesRoute
  '/guidelines': typeof GuidelinesIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guidelines': typeof GuidelinesRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/presentation': typeof PresentationRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/guidelines/expressions': typeof GuidelinesExpressionsRoute
  '/guidelines/functions': typeof GuidelinesFunctionsRoute
  '/guidelines/legends': typeof GuidelinesLegendsRoute
  '/guidelines/params': typeof GuidelinesParamsRoute
  '/guidelines/types': typeof GuidelinesTypesRoute
  '/guidelines/': typeof GuidelinesIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/guidelines'
    | '/playground'
    | '/presentation'
    | '/api/$'
    | '/demo/i18n'
    | '/demo/orpc-todo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/guidelines/expressions'
    | '/guidelines/functions'
    | '/guidelines/legends'
    | '/guidelines/params'
    | '/guidelines/types'
    | '/guidelines/'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/playground'
    | '/presentation'
    | '/api/$'
    | '/demo/i18n'
    | '/demo/orpc-todo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/guidelines/expressions'
    | '/guidelines/functions'
    | '/guidelines/legends'
    | '/guidelines/params'
    | '/guidelines/types'
    | '/guidelines'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/guidelines'
    | '/playground'
    | '/presentation'
    | '/api/$'
    | '/demo/i18n'
    | '/demo/orpc-todo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/guidelines/expressions'
    | '/guidelines/functions'
    | '/guidelines/legends'
    | '/guidelines/params'
    | '/guidelines/types'
    | '/guidelines/'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GuidelinesRoute: typeof GuidelinesRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  PresentationRoute: typeof PresentationRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DemoI18nRoute: typeof DemoI18nRoute
  DemoOrpcTodoRoute: typeof DemoOrpcTodoRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines/': {
      id: '/guidelines/'
      path: '/'
      fullPath: '/guidelines/'
      preLoaderRoute: typeof GuidelinesIndexRouteImport
      parentRoute: typeof GuidelinesRoute
    }
    '/guidelines/types': {
      id: '/guidelines/types'
      path: '/types'
      fullPath: '/guidelines/types'
      preLoaderRoute: typeof GuidelinesTypesRouteImport
      parentRoute: typeof GuidelinesRoute
    }
    '/guidelines/params': {
      id: '/guidelines/params'
      path: '/params'
      fullPath: '/guidelines/params'
      preLoaderRoute: typeof GuidelinesParamsRouteImport
      parentRoute: typeof GuidelinesRoute
    }
    '/guidelines/legends': {
      id: '/guidelines/legends'
      path: '/legends'
      fullPath: '/guidelines/legends'
      preLoaderRoute: typeof GuidelinesLegendsRouteImport
      parentRoute: typeof GuidelinesRoute
    }
    '/guidelines/functions': {
      id: '/guidelines/functions'
      path: '/functions'
      fullPath: '/guidelines/functions'
      preLoaderRoute: typeof GuidelinesFunctionsRouteImport
      parentRoute: typeof GuidelinesRoute
    }
    '/guidelines/expressions': {
      id: '/guidelines/expressions'
      path: '/expressions'
      fullPath: '/guidelines/expressions'
      preLoaderRoute: typeof GuidelinesExpressionsRouteImport
      parentRoute: typeof GuidelinesRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/orpc-todo': {
      id: '/demo/orpc-todo'
      path: '/demo/orpc-todo'
      fullPath: '/demo/orpc-todo'
      preLoaderRoute: typeof DemoOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuidelinesRouteChildren {
  GuidelinesExpressionsRoute: typeof GuidelinesExpressionsRoute
  GuidelinesFunctionsRoute: typeof GuidelinesFunctionsRoute
  GuidelinesLegendsRoute: typeof GuidelinesLegendsRoute
  GuidelinesParamsRoute: typeof GuidelinesParamsRoute
  GuidelinesTypesRoute: typeof GuidelinesTypesRoute
  GuidelinesIndexRoute: typeof GuidelinesIndexRoute
}

const GuidelinesRouteChildren: GuidelinesRouteChildren = {
  GuidelinesExpressionsRoute: GuidelinesExpressionsRoute,
  GuidelinesFunctionsRoute: GuidelinesFunctionsRoute,
  GuidelinesLegendsRoute: GuidelinesLegendsRoute,
  GuidelinesParamsRoute: GuidelinesParamsRoute,
  GuidelinesTypesRoute: GuidelinesTypesRoute,
  GuidelinesIndexRoute: GuidelinesIndexRoute,
}

const GuidelinesRouteWithChildren = GuidelinesRoute._addFileChildren(
  GuidelinesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GuidelinesRoute: GuidelinesRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  PresentationRoute: PresentationRoute,
  ApiSplatRoute: ApiSplatRoute,
  DemoI18nRoute: DemoI18nRoute,
  DemoOrpcTodoRoute: DemoOrpcTodoRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
